/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.util.*;

public class App {


    public static void main(String[] args) throws IOException {

     System.out.println("Running train booking System");
        Scanner scanner = new Scanner(System.in);
        int option = 0;
        boolean Check_for_login = false;
        UserBookingService userBookingService;
        try{
            userBookingService = new UserBookingService();
        } catch (IOException ex){
            System.out.println("There is something wrong!" + ex.getMessage());
            return;
        }
        Train trainSelectedForBooking = null;
        while(option!=7){
            System.out.println("choose option");
            System.out.println("1. Sign Up");
            System.out.println("2. login");
            System.out.println("3.Fetch Booking");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. cancel my Booking");
            System.out.println("7. Exit the App");
            option = scanner.nextInt();
            switch (option){
                case 1:
                    System.out.println("enter username to signup");
                    String nameToSignUp = scanner.next();
                    System.out.println("enter paasword to signup");
                    String passwordToSignUp = scanner.next();
                    User userToSignup = new User(nameToSignUp,
                            passwordToSignUp,
                            UserServiceUtil.hashPassword(passwordToSignUp),
                            new ArrayList<>(),
                            UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignup);
                    break;
                case 2:
                    System.out.println("enter username to login");
                    String username;

                      while(true){
                          username  = scanner.next();
                          if(username.contains(" ")){
                              System.out.println("username cannot contain spaces");
                          }
                          else {
                              break;
                          }

                      }
                    System.out.println("enter password to login");
                    String password = scanner.next();
                    Optional<User>foundUser = userBookingService.getUserByUsername(username);
                    if(foundUser.isPresent() &&
                            UserServiceUtil.checkPassword(
                                    password,foundUser.get().getHashedPassword())){
                        Check_for_login = true;
                        System.out.println("login sucessful! Welcome" + username);
                        userBookingService.setUser(foundUser.get());                    }
                    else {
                        System.out.println(" login failed");
                    }

                case 3:
                    try {
                        userBookingService.fetchBooking();
                    } catch (Exception e) {
                        System.out.println("There is something wrong");
                    }
                    break;
                case 4:
                    System.out.println("Enter source:");
                    scanner.nextLine(); // Consume leftover newline from previous input
                    String source = scanner.nextLine().toLowerCase();

                    System.out.println("Enter destination:");
                    String destination = scanner.nextLine().toLowerCase();

                    List<Train> trains = userBookingService.getTrains(source,destination);
                    if (trains.isEmpty()) {
                        System.out.println(" No trains available between " + source + " and " + destination);
                        break;
                    }
                    System.out.println("Available trains");
                    int index = 1;
                    for(Train t : trains){
                        System.out.println(index + ". Train ID: " + t.getTrainId() + " | Train No: " + t.getTrainNo());
                        System.out.println("   Route: " + String.join(" ➝ ", t.getStations()));
                        System.out.println("   Timings:");
                        for (Map.Entry<String, String> entry : t.getStationTimes().entrySet()) {
                            System.out.println("      " + entry.getKey() + " - " + entry.getValue());
                        }
                       index++;
                    }
                    System.out.println("Select a train by typing the corresponding number:");
                    int selectedIndex;
                    while (true) {
                        if (scanner.hasNextInt()) {
                            selectedIndex = scanner.nextInt();
                            scanner.nextLine(); // Consuming the newline character
                            if (selectedIndex > 0 && selectedIndex <= trains.size()) {
                                break;
                            } else {
                                System.out.println(" Invalid choice! Please select a valid train number.");
                            }
                        } else {
                            System.out.println(" Please enter a valid number.");
                            scanner.next(); // Clear invalid input
                        }
                    }

                    trainSelectedForBooking = trains.get(selectedIndex - 1); // Convert 1-based to 0-based index
                    System.out.println(" Train Selected: " + trainSelectedForBooking.getTrainId());

                    System.out.println("Available Seats:");
                    for (List<Integer> row : trainSelectedForBooking.getSeats()) {
                        for (Integer seat : row) {
                            System.out.print(seat + " ");
                        }
                        System.out.println();
                    }
                    break;

                case 5:
                    if (Check_for_login == false) {
                        System.out.println("❌ login first!");
                        break;
                    }
                    if (trainSelectedForBooking == null) {
                        System.out.println(" Please select a train first in option 4!");
                        break;
                    }
                    System.out.println("Select a seat out of these seats");

                    List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);

                    for (List<Integer> row: seats){
                        for (Integer val: row){
                            System.out.print(val +  " ");
                        }
                        System.out.println();
                    }

                    System.out.println("Select the seat by typing the row and column");

                    System.out.println("Enter the row");
                    int row = scanner.nextInt();

                    System.out.println("Enter the column");
                    int col = scanner.nextInt();

                    System.out.println("Booking your seat....");

                    Boolean booked = userBookingService.bookTrainSeat(trainSelectedForBooking, row, col);

                    if(booked.equals(Boolean.TRUE)){
                        System.out.println("Booked! Enjoy your journey");
                    }else{
                        System.out.println("Can't book this seat");
                    }
                    break;

                case 6:
                    if (Check_for_login == false) {
                        System.out.println("❌ login first!");
                        break;
                    }
                    System.out.println("Enter the ticket id to cancel the booking");
                    scanner.nextLine();
                    String ticketId = scanner.nextLine();
                    boolean isCancelled = userBookingService.cancelBooking(ticketId);

                    if(isCancelled){
                        System.out.println("Booking cancelled successfully!");
                    }
                    else{
                        System.out.println("Booking not found!");
                    }
                    break;



            }
        }


    }
}
